-- Active: 1776918534878@@127.0.0.1@3306@pemrograman_web_2
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `foto_profil` varchar(255) DEFAULT 'default.png',
  `role` enum('administrator','operator') NOT NULL DEFAULT 'operator',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `users` (`username`, `password`, `full_name`, `role`) VALUES
('admin1', MD5('password123'), 'Andi Pratama', 'administrator'),
('user2', MD5('password123'), 'Budi Santoso', 'operator'),
('user3', MD5('password123'), 'Citra Lestari', 'operator'),
('user4', MD5('password123'), 'Dedi Kurniawan', 'operator'),
('user5', MD5('password123'), 'Eka Putri', 'operator'),
('admin2', MD5('password123'), 'Fajar Hidayat', 'administrator'),
('user7', MD5('password123'), 'Gita Permata', 'operator'),
('user8', MD5('password123'), 'Hadi Wijaya', 'operator'),
('user9', MD5('password123'), 'Indah Sari', 'operator'),
('user10', MD5('password123'), 'Joko Susilo', 'operator'),
('user11', MD5('password123'), 'Kartika Dewi', 'operator'),
('user12', MD5('password123'), 'Lukas Setiawan', 'operator'),
('user13', MD5('password123'), 'Maya Anggraini', 'operator'),
('user14', MD5('password123'), 'Nanda Saputra', 'operator'),
('user15', MD5('password123'), 'Olivia Putri', 'operator'),
('admin3', MD5('password123'), 'Panji Asmoro', 'administrator'),
('user17', MD5('password123'), 'Qori Aina', 'operator'),
('user18', MD5('password123'), 'Rian Hidayat', 'operator'),
('user19', MD5('password123'), 'Santi Wijaya', 'operator'),
('user20', MD5('password123'), 'Taufik Rahman', 'operator'),
('user21', MD5('password123'), 'Umar Bakri', 'operator'),
('user22', MD5('password123'), 'Vina Panduwinata', 'operator'),
('user23', MD5('password123'), 'Wahyu Setiaji', 'operator'),
('user24', MD5('password123'), 'Xena Gabriella', 'operator'),
('user25', MD5('password123'), 'Yuda Pratama', 'operator'),
('user26', MD5('password123'), 'Zaskia Adya', 'operator'),
('user27', MD5('password123'), 'Agus Setiawan', 'operator'),
('user28', MD5('password123'), 'Bella Safira', 'operator'),
('user29', MD5('password123'), 'Chandra Malik', 'operator'),
('user30', MD5('password123'), 'Dina Lorenza', 'operator'),
('user31', MD5('password123'), 'Eko Prasetyo', 'operator'),
('user32', MD5('password123'), 'Fitri Handayani', 'operator'),
('user33', MD5('password123'), 'Gilang Dirga', 'operator'),
('user34', MD5('password123'), 'Hana Pertiwi', 'operator'),
('user35', MD5('password123'), 'Irfan Hakim', 'operator'),
('user36', MD5('password123'), 'Julia Perez', 'operator'),
('user37', MD5('password123'), 'Kevin Sanjaya', 'operator'),
('user38', MD5('password123'), 'Lala Karmela', 'operator'),
('user39', MD5('password123'), 'Mario Teguh', 'operator'),
('user40', MD5('password123'), 'Nina Zatulini', 'operator'),
('admin4', MD5('password123'), 'Onky Alexander', 'administrator'),
('user42', MD5('password123'), 'Putri Marino', 'operator'),
('user43', MD5('password123'), 'Robby Purba', 'operator'),
('user44', MD5('password123'), 'Sule Prikitiw', 'operator'),
('user45', MD5('password123'), 'Tora Sudiro', 'operator'),
('user46', MD5('password123'), 'Uus Komedi', 'operator'),
('user47', MD5('password123'), 'Vicky Prasetyo', 'operator'),
('user48', MD5('password123'), 'Wulan Guritno', 'operator'),
('user49', MD5('password123'), 'Yayan Ruhian', 'operator'),
('user50', MD5('password123'), 'Zumi Zola', 'operator'),
('user51', MD5('password123'), 'Abimana Aryasatya', 'operator'),
('user52', MD5('password123'), 'Bunga Citra', 'operator'),
('user53', MD5('password123'), 'Chico Jericho', 'operator'),
('user54', MD5('password123'), 'Dian Sastro', 'operator'),
('user55', MD5('password123'), 'Ello Tahitoe', 'operator'),
('user56', MD5('password123'), 'Fedi Nuril', 'operator'),
('user57', MD5('password123'), 'Giring Ganesha', 'operator'),
('user58', MD5('password123'), 'Hamish Daud', 'operator'),
('user59', MD5('password123'), 'Isyana Sarasvati', 'operator'),
('user60', MD5('password123'), 'Joe Taslim', 'operator'),
('user61', MD5('password123'), 'Kunto Aji', 'operator'),
('user62', MD5('password123'), 'Luna Maya', 'operator'),
('user63', MD5('password123'), 'Maudy Ayunda', 'operator'),
('user64', MD5('password123'), 'Nicholas Saputra', 'operator'),
('user65', MD5('password123'), 'Olla Ramlan', 'operator'),
('user66', MD5('password123'), 'Pevita Pearce', 'operator'),
('user67', MD5('password123'), 'Raisa Andriana', 'operator'),
('user68', MD5('password123'), 'Sari Nila', 'operator'),
('user69', MD5('password123'), 'Titi Kamal', 'operator'),
('user70', MD5('password123'), 'Ussy Sulistiawaty', 'operator'),
('admin5', MD5('password123'), 'Vino G Bastian', 'administrator'),
('user72', MD5('password123'), 'Widyawati', 'operator'),
('user73', MD5('password123'), 'Yuni Shara', 'operator'),
('user74', MD5('password123'), 'Zaskia Sungkar', 'operator'),
('user75', MD5('password123'), 'Ari Lasso', 'operator'),
('user76', MD5('password123'), 'Baim Wong', 'operator'),
('user77', MD5('password123'), 'Cinta Laura', 'operator'),
('user78', MD5('password123'), 'Deddy Corbuzier', 'operator'),
('user79', MD5('password123'), 'Eross Candra', 'operator'),
('user80', MD5('password123'), 'Fatin Shidqia', 'operator'),
('user81', MD5('password123'), 'Glenn Fredly', 'operator'),
('user82', MD5('password123'), 'Hesti Purwadinata', 'operator'),
('user83', MD5('password123'), 'Iwan Fals', 'operator'),
('user84', MD5('password123'), 'Judika Sihotang', 'operator'),
('user85', MD5('password123'), 'Krisdayanti', 'operator'),
('user86', MD5('password123'), 'Lesti Kejora', 'operator'),
('user87', MD5('password123'), 'Melly Goeslaw', 'operator'),
('user88', MD5('password123'), 'Najwa Shihab', 'operator'),
('user89', MD5('password123'), 'Once Mekel', 'operator'),
('user90', MD5('password123'), 'Pasha Ungu', 'operator'),
('user91', MD5('password123'), 'Rossa Roslaina', 'operator'),
('user92', MD5('password123'), 'Syahrini', 'operator'),
('user93', MD5('password123'), 'Tulus', 'operator'),
('user94', MD5('password123'), 'Ungu Band', 'operator'),
('user95', MD5('password123'), 'Vidi Aldiano', 'operator'),
('user96', MD5('password123'), 'Wali Band', 'operator'),
('user97', MD5('password123'), 'Xavier', 'operator'),
('user98', MD5('password123'), 'Yovie Widianto', 'operator'),
('user99', MD5('password123'), 'Ziva Magnolya', 'operator'),
('user100', MD5('password123'), 'Ahmad Dhani', 'operator');
UPDATE users SET password = MD5('user') WHERE id = 1;